### ISSUE TITLE
Weird problem with join model and dependent: :destroy

### ISSUE THREAD

**Issue by masterkain** [pixeltrix/sortifiable#5]
Hi,
I'm using sortifiable on Rails 3.2.1.

My model setup is like this:

``` ruby
class MediaFile < ActiveRecord::Base
  has_many :playlist_media_files, dependent: :destroy
  has_many :playlists, through: :playlist_media_files

# playlist_id, media_file_id, position
class PlaylistMediaFile < ActiveRecord::Base
  # WARNING: this will not delete this model record in case the MediaFile gets destroyed
  # and position attribute is not blank, but instead tries only to decrement this model position field.
  # As result  *_destroy callbacks for this model never runs, record will persist and
  # playlists.updated_at does not get touched, nor the counter cache decremented
  # (see belongs_to declaration below)
  acts_as_list scope: :playlist_id

  belongs_to :playlist, touch: true, counter_cache: true
  belongs_to :media_file
```

`playlist_media_files` has a column `position`.

When I try to `destroy` a `MediaFile` instance, the `dependent: :destroy` should wipe also the related `PlaylistMediaFile`, however if `position` _is not blank_ `acts_as_list`'s `before_destroy` kicks in, _but_ the `PlaylistMediaFile` instance won't continue its way to get destroyed, instead I see this:

```
(8.2ms)  SELECT id FROM `playlist_media_files` WHERE `playlist_media_files`.`playlist_id` = 7 AND (`position` IS NOT NULL) ORDER BY position FOR UPDATE
SQL (0.4ms)  UPDATE `playlist_media_files` SET `position` = `position` - 1 WHERE `playlist_media_files`.`playlist_id` = 7 AND (`position` IS NOT NULL) AND (`position` > 2292) ORDER BY position
# should delete the playlist_media_files record here, but it's not happening
SQL (0.4ms)  DELETE FROM `media_files` WHERE `media_files`.`type` IN ('AudioFile') AND `media_files`.`id` = 594341
```

**Comment by pixeltrix** [comment]
I think this [line](https://github.com/pixeltrix/sortifiable/blob/master/lib/sortifiable.rb#L390) is the cause of the problem - if it's not updated anything then it will return false and halt the callback chain. The question is why is it returning false - let me investigate it further and I'll get back to you later today. Does it work okay if you use `:dependent => :delete_all`?

**Comment by pixeltrix** [comment]
I've tried recreating your setup with a [test case](https://github.com/pixeltrix/sortifiable/commit/0de855fd5918f7c73fafdea22916fc02bcf08c9f) but I can't seem to reproduce it. The only thing I can think of is that the position column values are no longer sequential causing the update to fail. If you can make the test case fail I'll be happy to take another look at it - make a pull request against the [check-through-association-destroy](https://github.com/pixeltrix/sortifiable/tree/check-through-association-destroy) branch if you can.

The issue of position columns becoming out of sync is one area that needs addressing, not sure what's the best way to approach it though.

**Comment by masterkain** [comment]
To be clear,
my join model previously didn't have a position column, I added it afterwards for some quick testing/evaluationg if it was possible for me to do a certain thing, so I set a default value of 1:

```
playlist_id | media_file_id | position
1           | 2             | 1
1           | 3             | 1
```

I realize that this can have unwanted consequencies and I'm better off to regenerate positions properly, although we are talking about a lot of existing records.

Two things that concerns me:

1) in my specific use case not every media file needs a position against playlist, only the ones belonging to a certain owner class, that's why I put a 'default and forget' position, thinking it would be somewhat 'ok' even for record that does not use it
2) Callbacks not running properly on a model when position is 'out of sync' scares me, a lot, even because I wasn't able to catch this error through normal specs but during the app use (I have a 100%+ multiple test coverage)

Probably I'm better off rethinking about an alternative solution.

Thanks for your time.

**Comment by pixeltrix** [comment]
It's best to have a default value of NULL for the column that way you can add them to the list in a synchronised manner, e.g:

``` ruby
PlaylistMediaFile.find_each{ |f| f.add_to_list }
```

The problem with 'out of sync' lists is that it becomes pretty confusing because the methods start to do odd things like moving multiple items so that's why it halts if it detects a problem. Maybe it would be better just to log a warning rather than halting the callbacks, along with a command to resync the list - what do you think?

As for the callbacks, they can be halted by any callback method returning false and it often catches people out - ideally in Rails 4 it will be changed to explicit halting rather than being based on return value.

**Comment by masterkain** [comment]
Yeah, I think that Rails 4 already introduced an option for specifying a custom return value for which the callback must be halted (or when it can go on, don't remember) so we'll have far more control on the whole chain.

I'm going to try again later on setting the column default value to NULL, however what concerns me is referential integrity in the app's data, which can be undermined easily in a fast moving deploy/development cycle.

I'm trying my best to avoid situations, like in the previous version of the application, where counters, etc. can get out of sync due to silly bugs, because in this version they will be much more important; so any crucial pain point is well tested (as an example Rails' counter cache is still giving me nightmares).

In this case a warning I think is better suited rather than avoiding performing part of the callback chain, so +1 on that, but it's another thing that one must keep an eye on, and in a rather big application is kinda unwanted, because usually that's what test/specs are for.

I'll experiment a bit more though, thanks for your work on this gem ;)
