### ISSUE TITLE
update_position using wrong scope

### ISSUE THREAD

**Issue by stefankroes** [pixeltrix/sortifiable#6]
Currently this method uses list_class to perform the update.

We are using a paranoid delete solution that defined a default scope: where(:deleted_at => nil).

This means update_position should use base_scope instead because otherwise deleted nodes will not be updated.

We want deleted nodes to be included in the list because we want to be able to restore them to their original position.

Can you change this? It seems like a bug to me.

**Comment by pixeltrix** [comment]
@stefankroes it's definitely a bug however it only has a few edge cases where items are being added to and from the list. I managed to write a failing test so hopefully it should fix your problem. The diff is in 3b451bc6 and I've already pushed a new gem build.

**Comment by stefankroes** [comment]
Thx dude!
